### ISSUE TITLE
Alignment in Safari (iOS)

### ISSUE THREAD

**Issue by JoelSDavies** [danielgarthur/byzhtml#1]
Daniel- this project is awesome! The samples look great in desktop browsers already! Just FYI- alignment of modifiers isn’t great in Safari on iOS at the moment.
![C1A76A99-7040-4EFD-BF3E-A252E4C12653](https://user-images.githubusercontent.com/109194732/225813324-61a0fd88-0f52-4b27-91ed-dc29b11ffe74.png)

Thanks for all the work you are doing. Your work is a big help to us chanters.

**Comment by danielgarthur** [comment]
Thank you for your kind words. I'm glad you pointed this issue out, as I do not have an iPhone and don't regularly use Safari, so I did not even think to test it there.

Unfortunately, Safari lags behind Chrome and Firefox when it comes to advanced text features. I've updated the library to manually position the supporting neumes if a Webkit browser is detected (i.e. Safari, iOS, iPad, iPod). This should fix the alignment issues.

I still need to look into manually performing the contextual substitutions. For example, the antikenoma under an apostrofos should be replaced with a smaller antikenoma than the one used with the ison and oligon.

I tested what I have so far on Safari on a Mac desktop, and I used an iPhone simulator to test on the phone. But if you could test on your real phone, that would be great.

**Comment by JoelSDavies** [comment]
It looks much better now.

![974D8168-B46C-4F5D-93E1-EED1F79EA8C9](https://user-images.githubusercontent.com/109194732/226079435-ad16d604-c1c0-4525-bb2d-0dc3a2dcff26.png)

**Comment by danielgarthur** [comment]
Thanks for checking! That screenshot reminds me of the other issue on Safari, which is that the alignment of supporting neumes is not correct when a vareia is present. I'll try and manually adjust that, too, for webkit browsers.
